language: bash

before_install:
  - sudo apt install -y shellcheck p7zip-full imagemagick ghostscript 

script:
  - ls -l
  - shellcheck task1.sh
  - echo task1
  - bash task1.sh -h
  - bash task1.sh -q ./img 90
  - bash task1.sh -r ./img 90%
  - bash task1.sh -w ./img YYC center 200 
  - bash task1.sh -p ./img Pre
  - bash task1.sh -s ./img Suf
  - bash task1.sh -t ./img
  - shellcheck task2.sh
  - echo task2
  - bash task2.sh -h
  - bash task2.sh -a
  - bash task2.sh -p
  - bash task2.sh -n
  - bash task2.sh -m
  - shellcheck task3.sh
  - echo task3
  - bash task3.sh -h
  - bash task3.sh -t
  - bash task3.sh -i
  - bash task3.sh -u
  - bash task3.sh -s
  - bash task3.sh -c
  - bash task3.sh -f /images/NASA-logosmall.gif

notifications:
  email:
    on_success: never
